### ISSUE TITLE
add keyword in the package json

### ISSUE THREAD

**Issue by codescandy** [codescandy/dashui-free-nextjs-admin-template#4]
"keywords": [
    "react",
    "javascript",
    "admin",
   "dashboard",
   "nextjs",
"nextjs13",
   "admin-dashboard",
    "free",
    "mui",
    "admin-template",
    "admin-panel",
    "freebies",
    "nextjs-template",
    "react-dashboard",
 "bootstrap 5",
  ],

**Comment by fuadTamim1** [comment]
I tried it, it didn't work

**Comment by sandipthemes** [comment]
Added these keywords in package.json on v1.1.0 branch.
